// Code generated by hertz generator.

package greeting

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _greetingMw() []app.HandlerFunc {
	// your code...
	return nil
}
