// Code generated by hertz generator.

package greeting

import (
	"context"
	"time"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	greeting "hertz_demo/biz/model/demo/greeting"
)

// Greeting .
// @router /greeting [GET]
func Greeting(ctx context.Context, c *app.RequestContext) {
	var err error
	var req greeting.GreetingReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	name := req.Name
	if name == "" {
		name = "unknown"
	}

	// resp := new(greeting.GreetingResp)
	resp := greeting.GreetingResp{
		"0",
		"Hello, " + name + "! Welcome to hertz!",
		"ok",
		time.Now().UnixMilli(),
	}

	c.JSON(consts.StatusOK, resp)
}
