// Code generated by hertz generator.

package hello

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Hello .
// @router /hello [GET]
func Hello(ctx context.Context, c *app.RequestContext) {
	// 从请求中获取参数
	name := c.Query("name")

	if name == "" {
		name = "World"
	}

	c.JSON(consts.StatusOK, map[string]string{"msg": "Hello, " + name})
}
