// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	demo_greeting "hertz_demo/biz/router/demo/greeting"
	hello "hertz_demo/biz/router/hello"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	demo_greeting.Register(r)

	hello.Register(r)

}
